name: PixelStepper
options:
  bundleIdPrefix: com.pixelpalfit
  deploymentTarget:
    iOS: "16.2"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "2.1.0"
    CURRENT_PROJECT_VERSION: "2"

schemes:
  PixelPal:
    build:
      targets:
        PixelPal: all
    run:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release

targets:
  PixelPal:
    type: application
    platform: iOS
    sources:
      - path: PixelPal/Sources
      - path: PixelPal/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pixelpalfit.app
        INFOPLIST_FILE: PixelPal/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: PixelPal/PixelPal.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
    entitlements:
      path: PixelPal/PixelPal.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.security.application-groups:
          - group.com.pixelpalfit.app
    dependencies:
      - target: PixelPalWidget
        embed: true
    attributes:
      SystemCapabilities:
        com.apple.HealthKit:
          enabled: true
        com.apple.ApplicationGroups.iOS:
          enabled: true

  PixelPalWidget:
    type: app-extension
    platform: iOS
    product: PixelPalWidget
    sources:
      - path: PixelPalWidget/Sources
      - path: PixelPalWidget/Resources
      - path: PixelPal/Sources/Core/AvatarState.swift
      - path: PixelPal/Sources/Core/SharedData.swift
      - path: PixelPal/Sources/Core/SpriteAssets.swift
      - path: PixelPal/Sources/Core/PixelPalAttributes.swift
      - path: PixelPal/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pixelpalfit.app.widget
        INFOPLIST_FILE: PixelPalWidget/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: PixelPalWidget/PixelPalWidget.entitlements
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        SKIP_INSTALL: YES
    entitlements:
      path: PixelPalWidget/PixelPalWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.pixelpalfit.app
    attributes:
      SystemCapabilities:
        com.apple.ApplicationGroups.iOS:
          enabled: true
